# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsdiff < Formula
  desc "Filesystem changes tracking tool"
  homepage "https://github.com/falzm/fsdiff"
  version "0.4.0"

  on_macos do
    url "https://github.com/falzm/fsdiff/releases/download/v0.4.0/fsdiff_0.4.0-darwin-all.tar.gz"
    sha256 "773f53fd30a719508d9308ab7b3b9a0ea597f5beed334e0b2a85c6a3ca8f7b6d"

    def install
      bin.install "fsdiff"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/falzm/fsdiff/releases/download/v0.4.0/fsdiff_0.4.0-linux-amd64.tar.gz"
      sha256 "0a6981b63f6c46d3e9e2f28d508bdb0819ec36288289c3e87a739888964b0193"

      def install
        bin.install "fsdiff"
      end
    end
  end
end
