# This file was generated by GoReleaser. DO NOT EDIT.
class Fsdiff < Formula
  desc "Filesystem changes tracking tool"
  homepage "https://github.com/falzm/fsdiff"
  url "https://github.com/falzm/fsdiff/releases/download/v0.2.0/fsdiff_0.2.0-darwin-amd64.tar.gz"
  version "0.2.0"
  sha256 "0c80c58e9960d78d2015948bbae450a0f906423882ecc49e6b03a4b9a474f249"

  def install
    bin.install "fsdiff"
  end
end
